"""
Code generation templates for the scaffold CLI.

Each template is a Python string.Template.  Substitution variables:
  $name       — resource name in lowercase snake_case  (e.g. "widget")
  $Name       — resource name in TitleCase            (e.g. "Widget")
  $number     — zero-padded 3-digit migration number   (e.g. "006")
"""

from string import Template

# ─── Router template ──────────────────────────────────────────────────────────

ROUTER_TEMPLATE = Template('''\
"""
$Name router — /api/$name

Generated by: python -m scaffold router $name
Register in app/main.py:
    from app.routers import $name as ${name}_router
    app.include_router(${name}_router.router)
"""

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from typing import List

from app.database import get_db
from app.schemas import ${Name}Create, ${Name}Update, ${Name}Response
from app.auth import get_current_active_user, get_current_admin_user

router = APIRouter(prefix="/api/$name", tags=["$name"])


@router.get("", response_model=List[${Name}Response])
async def list_${name}s(
    db: AsyncSession = Depends(get_db),
    current_user=Depends(get_current_active_user),
):
    """List all ${name}s visible to the current user."""
    raise HTTPException(status_code=501, detail="Not implemented.")


@router.get("/{item_id}", response_model=${Name}Response)
async def get_${name}(
    item_id: int,
    db: AsyncSession = Depends(get_db),
    current_user=Depends(get_current_active_user),
):
    """Retrieve a single $name by ID."""
    raise HTTPException(status_code=501, detail="Not implemented.")


@router.post("", response_model=${Name}Response, status_code=201)
async def create_${name}(
    data: ${Name}Create,
    db: AsyncSession = Depends(get_db),
    current_user=Depends(get_current_active_user),
):
    """Create a new $name."""
    raise HTTPException(status_code=501, detail="Not implemented.")


@router.put("/{item_id}", response_model=${Name}Response)
async def update_${name}(
    item_id: int,
    data: ${Name}Update,
    db: AsyncSession = Depends(get_db),
    current_user=Depends(get_current_active_user),
):
    """Update a $name."""
    raise HTTPException(status_code=501, detail="Not implemented.")


@router.delete("/{item_id}")
async def delete_${name}(
    item_id: int,
    db: AsyncSession = Depends(get_db),
    current_user=Depends(get_current_admin_user),
):
    """Delete a $name (admin only)."""
    raise HTTPException(status_code=501, detail="Not implemented.")
''')

# ─── Schema stubs template ────────────────────────────────────────────────────

SCHEMA_STUB_TEMPLATE = Template('''\

# ─── $Name ────────────────────────────────────────────────────────────────────

class ${Name}Create(BaseModel):
    name: str
    # TODO: add fields


class ${Name}Update(BaseModel):
    name: Optional[str] = None
    # TODO: add fields


class ${Name}Response(BaseModel):
    id: int
    name: str
    # TODO: add fields
    created_at: datetime

    class Config:
        from_attributes = True
''')

# ─── Migration stub template ──────────────────────────────────────────────────

MIGRATION_TEMPLATE = Template('''\
-- Migration $number: $name
-- Generated by: python -m scaffold router $name

CREATE TABLE IF NOT EXISTS ${name}s (
    id         SERIAL PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    -- TODO: add columns
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_${name}s_name ON ${name}s(name);
''')
